use_frameworks!

target 'ConcentricProgressRingView_Example' do
    pod 'JBConcentricProgressRingView', :git => 'https://github.com/bleeckerj/JBConcentricProgressRingView.git'
    #pod 'ConcentricProgressRingView', :path => '../'
  #pod 'LionheartExtensions'

#  target 'ConcentricProgressRingView_Tests' do
#    inherit! :search_paths
#
#    pod 'Quick'
#    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
#  end
end
